// export const BASE_URL = process.env.NODE_ENV === 'development' ? 'http://localhost:5000' : ''

export const BASE_URL = ''
export const TEACHER_AUTH_URL = '/api'
export const TEACHER_URL = '/api/teacher'
export const ADMIN_URL = '/api/admin'
export const ADMIN_CLASS_URL = '/api/admin/class'
export const ADMIN_SECTION_URL = '/api/admin/section'
export const ADMIN_SUBJECT_URL = '/api/admin/subject'
export const ADMIN_HOUR_URL = '/api/admin/hour'
export const REPORT_URL = '/api/admin/report'
export const RESOURCE_URL = '/api/admin/resource'
export const TEACHER_RESOURCE_URL = '/api/resource'
export const PERIOD_URL = '/api/period'